[ru]
languageName = "Ru"
languageCode = "ru"
contentDir = "content"
weight = 1

[ru.params]
home = "Главная"
# copyright
copyright = " | by [@cretm](https://creio.ctlos.ru)"


# ################################### English language #####################################
# [en]
# languageName = "En"
# languageCode = "en-us"
# contentDir = "content/en"
# weight = 2

# [en.params]
# home = "Home"
# # copyright
# copyright = " | by [@cretm](https://creio.ctlos.ru)"
