################### navigation ####################

# header_top menu
[[header_top]]
name = "Работодателям"
url = "employers/"
weight = 1

[[header_top]]
name = "Ученикам и родителям"
url = "programs/"
weight = 2

[[header_top]]
name = "Учителям"
url = "programs/"
weight = 3


# main menu
[[main]]
name = "О нас"
url = "about/"
weight = 1

[[main]]
name = "Выбор вуза"
url = "programs/"
weight = 2

# [[main]]
# weight = 3
# name = "Страницы"
# hasChildren = true

#   [[main]]
#   parent = "Страницы"
#   name = "Университеты"
#   url = "universitety/"
#   weight = 1

#   [[main]]
#   parent = "Страницы"
#   name = "teacher"
#   url = "teacher/"

#   [[main]]
#   parent = "Страницы"
#   name = "event"
#   url = "event/"

#   [[main]]
#   parent = "Страницы"
#   name = "scholarship"
#   url = "scholarship/"

#   [[main]]
#   parent = "Страницы"
#   name = "research"
#   url = "research/"

[[main]]
name = "блог"
url = "blog/"
weight = 4

[[main]]
name = "города"
url = "cities/"
weight = 5
  
[[main]]
name = "Контакты"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "учителя"
url = "teacher/"

[[footer]]
name = "уведомления"
url = "notice/"

[[footer]]
name = "события"
url = "event/"

[[footer]]
name = "стипендия"
url = "scholarship/"

[[footer]]
name = "исследования"
url = "research/"


# footer_end
[[footer_end]]
name = "Помощь в поступлении в Китай"
url = "blog/pomoshch-v-postuplenie-v-kitaj/"
weight = 10

[[footer_end]]
name = "Рейтинг лучших университетов Китая"
url = "blog/rejtingi-kompas-v-mire-topovyh-vuzov/"
weight = 20

[[footer_end]]
name = "Гранты на обучение в Китае"
url = "blog/granti-v-kitae-2026/"
weight = 30

[[footer_end]]
name = "Особенности учебы в Китае"
url = "blog/ucheba-v-kitae-osobennosti/"
weight = 40

[[footer_end]]
name = "Зимний языковой лагерь в Китае"
url = "programs/zimnij-yazykovoj-lager-v-kitae/"
weight = 50

[[footer_end]]
name = "Летний языковой лагерь в Китае"
url = "programs/letnij-yazykovoj-lager-v-kitae-2/"
weight = 60
