################### navigation ####################

# header_top menu
[[header_top]]
name = "Работодателям"
url = "programs/russian_employers/"
weight = 10

[[header_top]]
name = "Ученикам и родителям"
url = "programs/uchenikam-i-roditelyam/"
weight = 20

[[header_top]]
name = "Учителям"
url = "programs/uchitelyam/"
weight = 30


# main menu
[[main]]
name = "О нас"
url = "about/"
weight = 1

[[main]]
name = "Выбор вуза"
weight = 2
hasChildren = true

  [[main]]
  parent = "Выбор вуза"
  name = "Программы"
  url = "programs/"
  weight = 10

  [[main]]
  parent = "Выбор вуза"
  name = "Университеты"
  url = "universities/"
  weight = 20

  [[main]]
  parent = "Выбор вуза"
  name = "Города"
  url = "cities/"

# [[main]]
# weight = 3
# name = "Страницы"
# hasChildren = true

#   [[main]]
#   parent = "Страницы"
#   name = "teacher"
#   url = "teacher/"

#   [[main]]
#   parent = "Страницы"
#   name = "event"
#   url = "event/"

#   [[main]]
#   parent = "Страницы"
#   name = "scholarship"
#   url = "scholarship/"

#   [[main]]
#   parent = "Страницы"
#   name = "research"
#   url = "research/"

[[main]]
name = "блог"
url = "blog/"
weight = 4

[[main]]
name = "Контакты"
url = "contacts/"
weight = 6


# footer menu
[[footer]]
name = "Почему Китай"
url = "programs/obuchenie-v-kitae/"
weight = 10

[[footer]]
name = "Выбрать вуз"
url = "universities/"
weight = 20

[[footer]]
name = "Гранты"
url = "programs/granty"
weight = 30

[[footer]]
name = "Публикации"
url = "blog/"
weight = 40

# [[footer]]
# name = "Отзывы"
# url = "blog/"
# weight = 50

[[footer]]
name = "Контакты"
url = "contacts/"
weight = 60

[[footer]]
name = "Партнёры"
url = "programs/nashi-partnery/"
weight = 70

[[footer]]
name = "Города"
url = "cities/"
weight = 80

[[footer]]
name = "Сведения об образовательной организации"
url = "programs/uchenikam-i-roditelyam/"
weight = 90

[[footer]]
name = "Соглашения с вузами"
url = "blog/soglasheniya-china-campus-s-kitajskimi-vuzami/"
weight = 100

[[footer]]
name = "Стажировки"
url = "programs/internships/"
weight = 110


# footer_end
[[footer_end]]
name = "Помощь в поступлении в Китай"
url = "blog/pomoshch-v-postuplenie-v-kitaj/"
weight = 10

[[footer_end]]
name = "Рейтинг лучших университетов Китая"
url = "blog/rejtingi-kompas-v-mire-topovyh-vuzov/"
weight = 20

[[footer_end]]
name = "Гранты на обучение в Китае"
url = "blog/granti-v-kitae-2026/"
weight = 30

[[footer_end]]
name = "Особенности учебы в Китае"
url = "blog/ucheba-v-kitae-osobennosti/"
weight = 40

[[footer_end]]
name = "Зимний языковой лагерь в Китае"
url = "programs/zimnij-yazykovoj-lager-v-kitae/"
weight = 50

[[footer_end]]
name = "Летний языковой лагерь в Китае"
url = "programs/letnij-yazykovoj-lager-v-kitae-2/"
weight = 60
